; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
lib_deps =
	symlink://lib/gpio
	symlink://lib/time

[env:test_native]
platform = native
test_framework = unity
lib_deps =
	symlink://lib/gpio_test
	symlink://lib/time_test

[env:mkrwan1310]
platform = atmelsam
board = mkrwan1310
test_ignore = *
framework = arduino
platform_packages = platformio/toolchain-gccarmnoneeabi@1.140201.0
lib_deps = 
	arduino-libraries/MKRWAN@^1.1.1
	arduino-libraries/ArduinoECCX08@^1.3.8
	symlink://lib/gpio_samd21
	symlink://lib/time_arduino
