---
name: generate stls

on:
  push:
    branches:
    - main
    paths:
    - '**.scad'

  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install OpenSCAD
        run: |
          sudo apt-get install -y --no-install-recommends openscad

      - name: generate stl files
        run: |
          ./generate-stls.sh

      - name: upload stls
        uses: actions/upload-artifact@v3
        with:
          name: stls
          path: generated

