---
name: generate stls

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '**.scad'

  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: install OpenSCAD
        run: |
          sudo apt-get install -y --no-install-recommends openscad

      - name: install stl-thumb
        run: |
          sudo apt-get install -y --no-install-recommends libosmesa6-dev
          wget https://github.com/unlimitedbacon/stl-thumb/releases/download/v0.5.0/stl-thumb_0.5.0_amd64.deb
          sudo dpkg -i stl-thumb_0.5.0_amd64.deb

      - name: generate stl files
        run: |
          ./generate-stls.sh

      - name: generate previews for stl files
        run: |
          stl-thumb generated/abluft_snapy/tisch-schlauchbefestigung.scad.stl generated/abluft_snapy/tisch-schlauchbefestigung.scad.png

      - name: update pull request with changed desgins
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2.8.1
        with:
          message: |
            "neue bilder sind da"

      - name: upload stls
        uses: actions/upload-artifact@v3
        with:
          name: stls
          path: generated

      - name: update generated stls
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update generated models"

