---
name: generate stls

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '**.scad'

  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install OpenSCAD
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends openscad

      - name: generate stl files
        run: |
          make all

      - name: upload stls
        uses: actions/upload-artifact@v4
        with:
          name: stls
          path: generated/new_stls

      - name: update generated stls
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update generated models"

